directory: /app/downloads
library: /app/data/beets/library.db

import:
  write: yes
  copy: no
  move: no
  resume: no
  quiet: yes
  autotag: yes
  timid: no
  singletons: yes

plugins:
  - chroma
  - fetchart
  - embedart
  - ftintitle
  - spotify

musicbrainz:
  searchlimit: 5
  genres: yes

acoustid:
  apikey: ""

spotify:
  mode: track
  tiebreak: popularity

match:
  strong_rec: 0.04
  medium_rec: 0.25
