"""add download retry fields

Revision ID: 96b5617a9d26
Revises: 759b9406838b
Create Date: 2026-08-02 12:37:04.806444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96b5617a9d26'
down_revision: Union[str, Sequence[str], None] = '759b9406838b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "songs",
        sa.Column(
            "download_retry_count",
            sa.Integer(),
            nullable=False,
            server_default="0",
        ),
    )

    op.add_column(
        "songs",
        sa.Column(
            "next_download_attempt",
            sa.DateTime(),
            nullable=True,
        ),
    )

    op.alter_column(
        "songs",
        "download_retry_count",
        server_default=None,
    )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('songs', 'next_download_attempt')
    op.drop_column('songs', 'download_retry_count')
    # ### end Alembic commands ###
