"""create playlists and songs tables

Revision ID: d07c97b6c79e
Revises: 
Create Date: 2026-07-31 12:15:24.000490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd07c97b6c79e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('playlists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('youtube_playlist_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_playlists_youtube_playlist_id'), 'playlists', ['youtube_playlist_id'], unique=True)
    op.create_table('songs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('playlist_id', sa.Integer(), nullable=False),
    sa.Column('youtube_video_id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('artist', sa.String(length=500), nullable=True),
    sa.Column('album', sa.String(length=500), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('download_status', sa.String(length=50), nullable=False),
    sa.Column('lyrics_status', sa.String(length=50), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=True),
    sa.Column('lyrics_path', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_songs_playlist_id'), 'songs', ['playlist_id'], unique=False)
    op.create_index(op.f('ix_songs_youtube_video_id'), 'songs', ['youtube_video_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_songs_youtube_video_id'), table_name='songs')
    op.drop_index(op.f('ix_songs_playlist_id'), table_name='songs')
    op.drop_table('songs')
    op.drop_index(op.f('ix_playlists_youtube_playlist_id'), table_name='playlists')
    op.drop_table('playlists')
    # ### end Alembic commands ###
