name: CI for Music-Sync
on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

env:
    DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USR }}
    DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
    ENV_FILE: .env
  
jobs:
    build-backend:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v7
              
            - name: Docker Login in GHCR
              uses: docker/login-action@v4
              with:
                username: ${{ env.DOCKER_USERNAME }}
                password: ${{ env.DOCKER_PASSWORD }}
                registry: ghcr.io
            
            - name: Build Backend Docker Image
              run: docker build -t music-sync-backend:latest .

            - name: Push Backend to GHCR
              run: | 
                docker tag music-sync-backend:latest ghcr.io/${{ github.repository_owner }}/music-sync-backend:${GITHUB_SHA}
                docker push ghcr.io/${{ github.repository_owner }}/music-sync-backend:${GITHUB_SHA}
                docker tag music-sync-backend:latest ghcr.io/${{ github.repository_owner }}/music-sync-backend:latest
                docker push ghcr.io/${{ github.repository_owner }}/music-sync-backend:latest

    build-frontend:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v7

            - name: Docker Login in GHCR
              uses: docker/login-action@v4
              with:
                username: ${{ env.DOCKER_USERNAME }}
                password: ${{ env.DOCKER_PASSWORD }}
                registry: ghcr.io

            - name: Build Frontend Docker Image
              run: docker build -t music-sync-frontend:latest ./dashboard

            - name: Push Frontend to GHCR
              run: | 
                docker tag music-sync-frontend:latest ghcr.io/${{ github.repository_owner }}/music-sync-frontend:${GITHUB_SHA}
                docker push ghcr.io/${{ github.repository_owner }}/music-sync-frontend:${GITHUB_SHA}
                docker tag music-sync-frontend:latest ghcr.io/${{ github.repository_owner }}/music-sync-frontend:latest
                docker push ghcr.io/${{ github.repository_owner }}/music-sync-frontend:latest

